[Admin] update utility workshop III entry with video link
OpenMobileAlliance/dmse-documentation pull request #76
Opened 2024-02-09 09:37 UTC by gocadimic

2024-02-10 18:40 UTC, jpradocueva commented on content/en/workshop.md
> +        <td><a href="https://app.hubspot.com/content-detail/21247113/landing-page/156126330626/performance" target="_blank">Download Presentation | Video</td>
@gocadimic. This doesn't seem to be the right link. I believe that Olivier has already changed the content on the landing page. Now it reads how to access the recording and presentation. See, https://21247113.hs-sites.com/revolutionizing-utilities-with-lwm2m-ecosystem-workshop-accesss-recording.

2024-02-10 18:40 UTC, jpradocueva requested changes
@gocadimic. This doesn't seem to be the right link. I believe that Olivier has already changed the content on the landing page. Now it reads how to access the recording and presentation. See, https://21247113.hs-sites.com/revolutionizing-utilities-with-lwm2m-ecosystem-workshop-accesss-recording.

2024-02-12 09:04 UTC, gocadimic commented
Resolved.

2024-02-12 14:58 UTC, jpradocueva approved these changes
@gocadimic, redy to merge.

2024-02-12 16:46 UTC, merged