add sve40 test results for Cumulocity
OpenMobileAlliance/dmse-documentation pull request #79
Opened 2024-02-15 19:41 UTC by gocadimic

2024-02-16 03:34 UTC, jpradocueva commented on content/en/listing.md
> +        <a href="https://www.openmobilealliance.org/test_events/VSVE-40/SVE-40_15-21-Nov-2023_Cumulocity-Server-LwM2M-v1_1-Test-Results.pdf" target="_blank">SVE-40 - Nov 2023 - Cumulocity v1.0 Server
@gocadimic The link is correct, but the title is incorrect; it indicates 1.0, but the link is for v1.1.

2024-02-16 03:35 UTC, jpradocueva requested changes
@gocadimic there is a problem with the title related to version v1.1

2024-02-19 02:22 UTC, jpradocueva commented on content/en/listing.md
> +        <a href="https://www.openmobilealliance.org/test_events/TF-35/Warsaw_2017_Nov-Cumulocity-Server-Posted-Results.pdf" target="_blank">TF Warsaw, Poland - Oct/Nov 2017 - Cumulocity v1.1 Server R
@gocadimic This event took place in 2017. There is no need to do the update here. Check the document and you will see the test is related to 1.0. You have rectified the problem in the Server, test event 2023.

2024-02-19 09:36 UTC, gocadimic commented on content/en/listing.md
> +        <a href="https://www.openmobilealliance.org/test_events/TF-35/Warsaw_2017_Nov-Cumulocity-Server-Posted-Results.pdf" target="_blank">TF Warsaw, Poland - Oct/Nov 2017 - Cumulocity v1.1 Server R
@jpradocueva, I made a mistake by missing a line. Now it's fixed.

2024-02-19 16:52 UTC, jpradocueva approved these changes
@gocadimic ready to merge and deploy. Thanks.

2024-02-19 19:18 UTC, merged